# Generated by Django 5.0.14 on 2026-07-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, default='', max_length=255)),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('categories', models.TextField(default='[]', help_text='JSON list of categories, e.g. ["City","Culture"]')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('best_season', models.CharField(blank=True, default='Year-round', max_length=100)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-rating'],
            },
        ),
    ]
