# Generated by Django 5.0.14 on 2026-07-13 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_preference', models.CharField(choices=[('budget', 'Budget'), ('mid', 'Mid-range'), ('luxury', 'Luxury')], default='mid', max_length=20)),
                ('travel_styles', models.TextField(default='[]', help_text='JSON list of selected travel styles e.g. ["Adventure","Cultural"]')),
                ('pace_of_travel', models.CharField(choices=[('leisurely', 'Leisurely (Relaxed & slow)'), ('moderate', 'Moderate'), ('fast', 'Fast-paced')], default='moderate', max_length=20)),
                ('accommodation_preference', models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('resort', 'Resort'), ('villa', 'Villa'), ('apartment', 'Apartment')], default='hotel', max_length=30)),
                ('dietary_requirements', models.CharField(blank=True, default='', max_length=200)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('miles_covered', models.PositiveIntegerField(default=0)),
                ('trips_count', models.PositiveIntegerField(default=0)),
                ('membership_year', models.PositiveIntegerField(default=2024)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
