# Generated by Django 5.0.14 on 2026-07-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenGem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('why_special', models.TextField(blank=True, default='')),
                ('transport_info', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('Nature', 'Nature'), ('Culture', 'Culture'), ('Food', 'Food'), ('Architecture', 'Architecture'), ('Adventure', 'Adventure'), ('Spiritual', 'Spiritual'), ('Scenic', 'Scenic')], default='Nature', max_length=50)),
                ('location_label', models.CharField(blank=True, default='', max_length=200)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_gems', to='destinations.destination')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
